# Generated by Django 6.0.2 on 2026-02-21 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_demo_alter_video_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
