# Generated by Django 6.0.2 on 2026-03-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_dailyxp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userxp',
            name='has_seen_welcome',
            field=models.BooleanField(default=False, help_text='Whether user has seen welcome page after signup'),
        ),
    ]
