# Generated by Django 6.0.2 on 2026-03-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_alter_userprogress_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='xp_chunks_awarded',
            field=models.PositiveIntegerField(default=0, help_text='Number of XP chunks awarded for this lesson'),
        ),
    ]
