# Generated by Django 6.0.2 on 2026-03-04 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_userprogress_xp_chunks_awarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResourceAzure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('pfp', 'Profile Picture'), ('video', 'Video'), ('thumbnail', 'Thumbnail')], help_text='Type of resource: Profile Picture, Video, or Thumbnail', max_length=10)),
                ('blob_url', models.URLField(help_text='Full URL to Azure Blob Storage file')),
                ('blob_name', models.CharField(help_text='Blob name in Azure container', max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('label', models.CharField(blank=True, help_text="Optional label (e.g., 'Intro Video', 'Course Thumbnail')", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azure_resources', to='video.course')),
            ],
            options={
                'verbose_name_plural': 'Course Resources (Azure)',
                'ordering': ['resource_type', 'order', 'created_at'],
                'indexes': [models.Index(fields=['course', 'resource_type'], name='video_cours_course__9a4546_idx')],
            },
        ),
    ]
