# Generated by Django 6.0.2 on 2026-03-05 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_courseresourceazure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='courseresourceazure',
            name='video_cours_course__9a4546_idx',
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='dailyxp',
            index=models.Index(fields=['user', 'date'], name='dailyxp_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyxp',
            index=models.Index(fields=['user', '-date'], name='dailyxp_user_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user'], name='enrollment_user_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'course'], name='enrollment_user_course_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'completed'], name='userprog_user_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'course'], name='userprog_user_course_idx'),
        ),
        migrations.DeleteModel(
            name='CourseResourceAzure',
        ),
    ]
