# Generated by Django 6.0.2 on 2026-03-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_discussion_liked_by'),
        ('video', '0014_remove_courseresourceazure_video_cours_course__9a4546_idx_and_more'),
    ]

    operations = [
    ]
