# Generated by Django 6.0.2 on 2026-03-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0015_merge_20260305_1243'),
        ('video', '0015_merge_20260306_0949'),
    ]

    operations = [
    ]
