"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import json

# Resolve key project paths early so env loading is independent of current working directory.
SETTINGS_DIR = Path(__file__).resolve().parent
BASE_DIR = SETTINGS_DIR.parent

def _load_simple_env_file(path):
    """Fallback loader for KEY=VALUE .env files when python-dotenv is unavailable."""
    try:
        with open(path, 'r', encoding='utf-8') as env_file:
            for raw_line in env_file:
                line = raw_line.strip()
                if not line or line.startswith('#') or '=' not in line:
                    continue
                key, value = line.split('=', 1)
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if key and key not in os.environ:
                    os.environ[key] = value
    except FileNotFoundError:
        pass

# Load environment variables from Backend/.env (local development only).
# Avoid relying on current working directory; this prevents stale values from other .env files.
_backend_env_path = BASE_DIR / '.env'
try:
    from dotenv import load_dotenv
    load_dotenv(_backend_env_path)
except ImportError:
    _load_simple_env_file(_backend_env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-*oki0j(n=i3o8)7%hkn%)cvj0ro-(+g6%2!(th+kqsmf^6h_ku')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Allow all hosts for development; set explicit hosts in production via env
_env_hosts = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]
ALLOWED_HOSTS = _env_hosts if _env_hosts else [
    '20.17.98.254.nip.io',
    'scopio.in',
    'www.scopio.in',
    '20.17.98.254',
    'localhost',
    '127.0.0.1',
]
# Django REST Framework + JWT
_default_renderers = ["rest_framework.renderers.JSONRenderer"]
if DEBUG:
    _default_renderers.append("rest_framework.renderers.BrowsableAPIRenderer")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": _default_renderers,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    # Safer refresh handling
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# Resolve Google OAuth credentials from env or a local JSON file
def _get_google_oauth_creds():
    cid = os.getenv('GOOGLE_CLIENT_ID', '')
    secret = os.getenv('GOOGLE_CLIENT_SECRET', '')
    if cid and secret:
        return cid, secret
    json_path = os.getenv('GOOGLE_OAUTH_JSON_PATH', str(BASE_DIR / 'google-oauth-client.json'))
    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        block = data.get('web') or data.get('installed') or data
        cid2 = block.get('client_id', '')
        sec2 = block.get('client_secret', '')
        if cid2 and sec2:
            return cid2, sec2
    except Exception:
        pass
    return cid, secret

GOOGLE_CLIENT_ID_VAL, GOOGLE_CLIENT_SECRET_VAL = _get_google_oauth_creds()

# Application definition
SITE_ID = 1
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'corsheaders',  # For handling CORS
    'glogin',
    # Allauth apps for social authentication
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # Enable JWT token blacklisting when rotating refresh tokens
    'rest_framework_simplejwt.token_blacklist',
    'embed_video',  # For embedding videos in Django models
    'video',
    'storages',
    
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'consent',
        },
        'APP': {
            'client_id': GOOGLE_CLIENT_ID_VAL,
            'secret': GOOGLE_CLIENT_SECRET_VAL,
            'key': ''
        },
        'VERIFIED_EMAIL': False,
        'VERSION': 'v2',
    }
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # MUST be first for CORS preflight
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.http.ConditionalGetMiddleware',
    "django.middleware.common.CommonMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add custom templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Uses PostgreSQL hosted on NeonDB
# DATABASE_URL environment variable is required

_database_url = (os.getenv('DATABASE_URL') or '').strip()

if not _database_url:
    raise RuntimeError(
        "❌ DATABASE_URL environment variable is required. "
        "Configure your PostgreSQL connection string from NeonDB."
    )

# Use Neon PostgreSQL
try:
    import urllib.parse
    # Handle special characters in password
    parsed = urllib.parse.urlparse(_database_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path[1:],
            'USER': parsed.username,
            'PASSWORD': parsed.password,
            'HOST': parsed.hostname,
            'PORT': parsed.port or 5432,
            'CONN_MAX_AGE': 600,
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }
    print(f"[OK] Using PostgreSQL/Neon: {parsed.hostname}")
except Exception as e:
    raise RuntimeError(f"[ERROR] Failed to parse DATABASE_URL: {e}")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.parent / 'storage'

AZURE_STORAGE_CONNECTION_STRING = os.getenv('AZURE_STORAGE_CONNECTION_STRING', '')
AZURE_ACCOUNT_NAME = (os.getenv('AZURE_ACCOUNT_NAME') or os.getenv('AZURE_STORAGE_ACCOUNT_NAME', '')).strip()
AZURE_ACCOUNT_KEY = (os.getenv('AZURE_ACCOUNT_KEY') or os.getenv('AZURE_STORAGE_ACCOUNT_KEY', '')).strip()
AZURE_PROFILE_PFP_CONTAINER = (
    os.getenv('AZURE_PROFILE_PFP_CONTAINER') or os.getenv('AZURE_CONTAINER_PFP', 'pfp')
).strip()
AZURE_OBJECT_PARAMETERS = {
    'cache_control': 'public, max-age=2592000, immutable',
}
DEFAULT_PROFILE_IMAGE_BLOB = os.getenv('DEFAULT_PROFILE_IMAGE_BLOB', 'defaults/profileDefault.webp')
if AZURE_STORAGE_CONNECTION_STRING or (AZURE_ACCOUNT_NAME and AZURE_ACCOUNT_KEY):
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.azure_storage.AzureStorage',
            'OPTIONS': {
                'connection_string': AZURE_STORAGE_CONNECTION_STRING,
                'account_name': AZURE_ACCOUNT_NAME,
                'account_key': AZURE_ACCOUNT_KEY,
                'azure_container': AZURE_PROFILE_PFP_CONTAINER,
                'overwrite_files': False,
            },
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

REDIS_URL = os.getenv('REDIS_URL', '').strip()
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': 300,
            'OPTIONS': {
                'socket_connect_timeout': 5,
                'socket_timeout': 5,
            },
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'scopio-default-cache',
            'TIMEOUT': 300,
        }
    }

# CORS/CSRF origins for both environments
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://scopio-webapp.pages.dev').rstrip('/')
USE_HTTPS = os.getenv('USE_HTTPS', ('False' if DEBUG else 'True')).lower() in ('true', '1', 'yes')

_default_frontend_origins = [
    'http://localhost:5173',
    'https://scopio-webapp.pages.dev',
]

_env_frontend_origins = [
    o.strip().rstrip('/')
    for o in os.getenv('FRONTEND_ALLOWED_ORIGINS', '').split(',')
    if o.strip()
]

FRONTEND_ALLOWED_ORIGINS = _env_frontend_origins if _env_frontend_origins else _default_frontend_origins
if FRONTEND_URL and FRONTEND_URL not in FRONTEND_ALLOWED_ORIGINS:
    FRONTEND_ALLOWED_ORIGINS.append(FRONTEND_URL)

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = FRONTEND_ALLOWED_ORIGINS

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrftoken',
]
CORS_PREFLIGHT_MAX_AGE = 86400  # Cache preflight for 24 hours

CSRF_TRUSTED_ORIGINS = [
    'https://scopio-webapp.pages.dev',
    'https://20.17.98.254.nip.io',
]

# Cookie settings for cross-domain authentication
if DEBUG:
    # Development: localhost same-origin
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = False
    SESSION_COOKIE_DOMAIN = None
    SECURE_SSL_REDIRECT = False
else:
    # Production requires secure cross-site cookies for Vercel -> Django auth flows.
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = USE_HTTPS
    # Don't set SESSION_COOKIE_DOMAIN - let browser handle it
    SESSION_COOKIE_DOMAIN = None

CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
SESSION_COOKIE_HTTPONLY = True  # Security: Don't expose session to JS
CSRF_COOKIE_NAME = 'csrftoken'
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_AGE = 86400 * 7  # 7 days
SESSION_SAVE_EVERY_REQUEST = True  # Prevent cold-start session loss
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Store in PostgreSQL

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Default authentication
    'allauth.account.auth_backends.AuthenticationBackend',  # For social auth
)

LOGIN_REDIRECT_URL = '/glogin/google/finalize/'  # Complete OAuth by minting JWT and redirecting to frontend
LOGOUT_REDIRECT_URL = '/'  # Redirect to home after logout
ACCOUNT_SIGNUP_REDIRECT_URL = '/glogin/google/finalize/'
ACCOUNT_LOGIN_REDIRECT_URL = '/glogin/google/finalize/'

# allauth configuration to avoid intermediate forms and auto-create users
# Using new allauth v0.65+ settings
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'

# Enforce stronger defaults in production
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Don't require email verification for social login
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https' if (not DEBUG) else 'http'
SOCIALACCOUNT_ADAPTER = 'glogin.adapter.SocialAdapter'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
LOGIN_ERROR_URL = '/glogin/error/'  # Redirect authentication errors to custom handler

# Trust X-Forwarded-Proto headers from nginx reverse proxy only when HTTPS is enabled.
# Using 'http' here would incorrectly mark every request as secure and force HTTPS callback URLs.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if (not DEBUG and USE_HTTPS) else None

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if DEBUG else 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'glogin': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'allauth': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}
